name: GameProDevVanish
version: '${project.version}'
main: de.gameprodev.gameProDevVanish.GameProDevVanish
api-version: '1.21'
author: GameProDev
commands:
  vanish:
    usage: /vanish
    permission: gameprodevvanish.vanish
permissions:
  gameprodevvanish.vanish:
    default: op
  gameprodevvanish.see:
    default: op
